"""create lesson_pdfs table

Revision ID: 339f6ad7df18
Revises: f4a98c9e4c11
Create Date: 2026-04-14 11:39:35.357184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '339f6ad7df18'
down_revision: Union[str, Sequence[str], None] = 'f4a98c9e4c11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_pdfs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('pdf_url', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_pdfs_lesson_id'), 'lesson_pdfs', ['lesson_id'], unique=False)
    op.alter_column('lessons', 'video_embed_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('lessons', 'pdf_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('password_reset_tokens_token_key'), 'password_reset_tokens', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('password_reset_tokens_token_key'), 'password_reset_tokens', ['token'], postgresql_nulls_not_distinct=False)
    op.alter_column('lessons', 'pdf_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('lessons', 'video_embed_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_lesson_pdfs_lesson_id'), table_name='lesson_pdfs')
    op.drop_table('lesson_pdfs')
    # ### end Alembic commands ###
