"""add last_name to users

Revision ID: e767d6abcf7c
Revises: c1e2cde61b24
Create Date: 2026-03-29 17:00:16.652060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e767d6abcf7c'
down_revision: Union[str, Sequence[str], None] = 'c1e2cde61b24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_name', sa.String(length=120), nullable=True))
    op.execute("UPDATE users SET last_name = name WHERE last_name IS NULL")
    op.alter_column('users', 'last_name', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    # ### end Alembic commands ###
